---
title: Missing Date Checker Overview
---
classDiagram
    class MissingDateChecker {
        +sqlite_name: str
        +city: str
        +find_missing_dates_in_db(year: int) list[str]
        +check_missing_dates(count_of_date_by_mth_asof_today_list: list[tuple], current_month: str, missing_date_list: list[str], today: datetime.datetime, year: int) None
        +find_dates_of_the_month_in_db(days_in_month: int, month: int, year: int) tuple
    }

    class BookingDetailsParam {
        +city: str
        +group_adults: int
        +num_rooms: int
        +group_children: int
        +selected_currency: str
        +scrape_only_hotel: bool
        +sqlite_name: str
    }

    class BasicGraphQLScraper {
        +sqlite_name: str
        +city: str
        +country: str
        +check_in: str
        +check_out: str
        +group_adults: int
        +num_rooms: int
        +group_children: int
        +selected_currency: str
        +scrape_only_hotel: bool
        +url: str
        +headers: dict
        +data: dict
        +scrape_graphql() pd.DataFrame
        #_get_response_data(graphql_query: dict) dict
        #_fetch_hotel_data(total_page_num: int) tuple[Any]
        #_validate_inputs() bool
        #_get_graphql_query(page_offset: int = 0) dict
        #_check_currency_data() str
        #_check_city_data() str
        #_check_hotel_filter_data() bool
        #_check_country_data() str
        +check_info() tuple[int, dict]
        #_find_total_page_num() int
    }

    MissingDateChecker --> BasicGraphQLScraper : Uses
    MissingDateChecker --> BookingDetailsParam : Associated with
