---
title: Scraper Overview
---
classDiagram
    class BasicGraphQLScraper {
        +sqlite_name: str
        +city: str
        +country: str
        +check_in: str
        +check_out: str
        +group_adults: int
        +num_rooms: int
        +group_children: int
        +selected_currency: str
        +scrape_only_hotel: bool
        +url: str
        +headers: dict
        +data: dict
        +scrape_graphql() pd.DataFrame
        #_get_response_data(graphql_query: dict) dict
        #_fetch_hotel_data(total_page_num: int) tuple[Any]
        #_validate_inputs() bool
        #_get_graphql_query(page_offset: int = 0) dict
        #_check_currency_data() str
        #_check_city_data() str
        #_check_hotel_filter_data() bool
        #_check_country_data() str
        +check_info() tuple[int, dict]
        #_find_total_page_num() int
        #_scrape_data_from_endpoint(total_page_num: int) list[Any]
        #_log_initial_details() None
    }


    class WholeMonthGraphQLScraper {
        +year: int
        +month: int
        +start_day: int
        +nights: int

        +scrape_whole_month(timezone=None) pd.DataFrame
    }

    class JapanScraper {
        +japan_regions: dict
        +duckdb_path: str
        +region: str
        +start_month: int
        +end_month: int

        +scrape_japan_hotels() None
        #_scrape_whole_year() None
        #_load_to_duckdb(prefecture_hotel_data: pd.DataFrame)
    }

    class AutomatedScraper {
        +main() None
    }

    BasicGraphQLScraper <|-- WholeMonthGraphQLScraper
    WholeMonthGraphQLScraper <|-- JapanScraper
    WholeMonthGraphQLScraper <|-- AutomatedScraper